; Uniwersalne flagi dla wszystkich środowisk
[env]
build_flags = 
    -std=gnu++17

; Baza sprzętowa specjalnie dla ESP32
[env:esp32_base]
platform = espressif32
board = esp32dev
framework = arduino
upload_speed = 921600
monitor_speed = 115200

; Środowiska sprzętowe (dziedziczą z bazy ESP)
[env:i2c_scanner]
extends = env:esp32_base
build_src_filter = -<*> +<tests/I2C_scanner.cpp>

[env:main]
extends = env:esp32_base
build_src_filter = -<*> +<main.cpp>

; Czyste środowisko dla PC (izolowane od sprzętu)
[env:buffer_testing]
platform = native
build_src_filter = -<*> +<tests/test_ring_buffer.cpp> 